language: node_js
node_js:
    - '8'   # EOL at 2019-12-31
    - '10'  # EOL at 2021-04-01
    - '12'  # EOL at 2022-04-01
branches:
    only:
        - master

script:
    - 'npm run build'       # build with tsc
    - 'npm run coverage'    # test and generate coveage
    - 'npm run coveralls'   # send coverage